/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zabdy
 */
public class catalogoDepar extends javax.swing.JInternalFrame {

    /**
     * Creates new form catalogoDepar
     */
    public catalogoDepar() {
        initComponents();
        catalodepartamento("");
        bloquear();
    }
String idDepart;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
void desbloquear(){
txtCat_Depart.setEnabled(true);
txtdescdepar.setEnabled(true);
jButton1.setEnabled(false);
jButton9.setEnabled(true);
jButton15.setEnabled(true);
ActualizarCat_Depart.setEnabled(true);
jButton2.setEnabled(true);
BotonCat_Depart.setEnabled(true);
}
void bloquear(){
txtCat_Depart.setEnabled(false);
txtdescdepar.setEnabled(false);
jButton1.setEnabled(true);
jButton9.setEnabled(false);
jButton15.setEnabled(false);
ActualizarCat_Depart.setEnabled(false);
jButton2.setEnabled(true);
BotonCat_Depart.setEnabled(false);
}
void limpiar(){
txtCat_Depart.setText("");
txtdescdepar.setText("");

}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuCatalogoDepartamento = new javax.swing.JPopupMenu();
        ModificarDepartamento = new javax.swing.JMenuItem();
        EliminarDeparatamento = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabladepartamento = new javax.swing.JTable();
        BotonCat_Depart = new javax.swing.JButton();
        txtCat_Depart = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtdescdepar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        ActualizarCat_Depart = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        ModificarDepartamento.setText("Modificar");
        ModificarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarDepartamentoActionPerformed(evt);
            }
        });
        MenuCatalogoDepartamento.add(ModificarDepartamento);

        EliminarDeparatamento.setText("Eliminar");
        EliminarDeparatamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDeparatamentoActionPerformed(evt);
            }
        });
        MenuCatalogoDepartamento.add(EliminarDeparatamento);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Catalogo de Dapartamentos");

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));

        tabladepartamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabladepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabladepartamento.setComponentPopupMenu(MenuCatalogoDepartamento);
        jScrollPane5.setViewportView(tabladepartamento);

        BotonCat_Depart.setText("Buscar");
        BotonCat_Depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCat_DepartActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("Descripcion del Deparatamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtdescdepar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdescdepar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton9.setText("Guardar Dato");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton15.setText("Limpiar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        ActualizarCat_Depart.setText("Actualizar");
        ActualizarCat_Depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarCat_DepartActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ActualizarCat_Depart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActualizarCat_Depart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCat_Depart, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonCat_Depart, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCat_Depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCat_Depart))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        String  des;

        String sql="";

        des = txtdescdepar.getText();

        sql= "INSERT INTO cat_departamento (DESC_DEPARTAMENTO) VALUES (?)";
        try {
            PreparedStatement psd = cn.prepareStatement(sql);

            psd.setString(1,des);

            int n= psd.executeUpdate();
            if (n>0){

                JOptionPane.showMessageDialog(null, "REGISTRO GUARDADO CON EXITO");

            }
        } catch (SQLException ex) {
            Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
limpiar();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void ActualizarCat_DepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarCat_DepartActionPerformed
        // TODO add your handling code here:
        try {
            String ID_DEPARTAMENTO = idDepart;
            String DESC_Depart = txtdescdepar.getText();

            PreparedStatement psd = cn.prepareStatement("UPDATE cat_departamento SET DESC_DEPARTAMENTO='" +
                DESC_Depart +

                "' WHERE ID_DEPARTAMENTO= '"
                +ID_DEPARTAMENTO + "'");

            int n = psd.executeUpdate();
            System.out.println(n);
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Registro Actualizado");
            } else {
                JOptionPane.showMessageDialog(null, "No Se Puede Actualizar Tu Registro ");
            }
            catalodepartamento("");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_ActualizarCat_DepartActionPerformed

    private void BotonCat_DepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCat_DepartActionPerformed
        // TODO add your handling code here:
        catalodepartamento(txtCat_Depart.getText());
    }//GEN-LAST:event_BotonCat_DepartActionPerformed

    private void ModificarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarDepartamentoActionPerformed
        // TODO add your handling code here:
        int fila = tabladepartamento.getSelectedRow();

        idDepart = tabladepartamento.getValueAt(fila, 0).toString();
        txtdescdepar.setText(tabladepartamento.getValueAt(fila, 1).toString());

    }//GEN-LAST:event_ModificarDepartamentoActionPerformed

    private void EliminarDeparatamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDeparatamentoActionPerformed
        // TODO add your handling code here:

        int fila = tabladepartamento.getSelectedRow();
        String cod="";
        cod=tabladepartamento.getValueAt(fila, 0).toString();

        try {
            PreparedStatement pst;
            pst = cn.prepareStatement("DELETE FROM cat_departamento WHERE  ID_DEPARTAMENTO ='"+cod+"'");
            pst.executeUpdate();
            catalodepartamento("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Puedes Eliminar Esta FILA Hasta Borrar Sus Relaciones");
        }

    }//GEN-LAST:event_EliminarDeparatamentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        desbloquear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

 void catalodepartamento (String valor){
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("ID DEL DEPARTAMENTO");
    modelo.addColumn("DESCRIPCION DEL DEPARTAMENTO");
    
    
    tabladepartamento.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM cat_departamento";
    }
    else{
        sql="SELECT * FROM cat_departamento WHERE ID_DEPARTAMENTO='"+valor+"'";
    }
 
    String []datos = new String [2];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                
                datos[1]=rs.getString(2);
                
                modelo.addRow(datos);
            }
            tabladepartamento.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(COnsul.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarCat_Depart;
    private javax.swing.JButton BotonCat_Depart;
    private javax.swing.JMenuItem EliminarDeparatamento;
    private javax.swing.JPopupMenu MenuCatalogoDepartamento;
    private javax.swing.JMenuItem ModificarDepartamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabladepartamento;
    private javax.swing.JTextField txtCat_Depart;
    private javax.swing.JTextField txtdescdepar;
    // End of variables declaration//GEN-END:variables
conecta cc=new conecta ();
Connection cn=cc.conexion();
}
