/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zabdy
 */
public class Cataloproduc extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cataloproduc
     */
    public Cataloproduc() {
        initComponents();
        catalogoproduc("");
  cat_produ();
  cat_produ2();
  bloquear();
    }
  String idproduc;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  void bloquear(){
  txtCan_Produ.setEnabled(false);
      txtCantidad.setEnabled(false);
       txtCat_producto.setEnabled(false);
        txtDesc_Produc.setEnabled(false);
         txtIVA.setEnabled(false);
          txtPesoSM.setEnabled(false);
           txtPesoUM.setEnabled(false);
            txtPesoUnitarioComp.setEnabled(false);
             txtPesoUnitarioVenta.setEnabled(false);
       comboID_Unidad_Medida.setEnabled(false);
  comboIDdescripcion.setEnabled(false);
  jButton1.setEnabled(true);
  jButton11.setEnabled(false);
  ActualizarCat_producto.setEnabled(false);
  BotonConsultar.setEnabled(false);
  jButton2.setEnabled(true);
  }
  void desbloquear(){
  txtCan_Produ.setEnabled(true);
      txtCantidad.setEnabled(true);
       txtCat_producto.setEnabled(true);
        txtDesc_Produc.setEnabled(true);
         txtIVA.setEnabled(true);
          txtPesoSM.setEnabled(true);
           txtPesoUM.setEnabled(true);
            txtPesoUnitarioComp.setEnabled(true);
             txtPesoUnitarioVenta.setEnabled(true);
       comboID_Unidad_Medida.setEnabled(true);
  comboIDdescripcion.setEnabled(true);
  jButton1.setEnabled(false);
  jButton11.setEnabled(true);
  ActualizarCat_producto.setEnabled(true);
  BotonConsultar.setEnabled(true);
  jButton2.setEnabled(true);
  }
  void limpiar(){
  
  txtCan_Produ.setText("");
      txtCantidad.setText("");
       txtCat_producto.setText("");
        txtDesc_Produc.setText("");
         txtIVA.setText("");
          txtPesoSM.setText("");
           txtPesoUM.setText("");
            txtPesoUnitarioComp.setText("");
             txtPesoUnitarioVenta.setText("");
  }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuCat_producto = new javax.swing.JPopupMenu();
        ModificarCat_producto = new javax.swing.JMenuItem();
        EliminarCat_producto = new javax.swing.JMenuItem();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        txtCat_producto = new javax.swing.JTextField();
        BuscarCat_producto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtPesoSM = new javax.swing.JTextField();
        txtPesoUM = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        txtCan_Produ = new javax.swing.JTextField();
        comboIDdescripcion = new javax.swing.JComboBox<>();
        txtPesoUnitarioVenta = new javax.swing.JTextField();
        txtPesoUnitarioComp = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        comboID_Unidad_Medida = new javax.swing.JComboBox<>();
        txtDesc_Produc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        BotonConsultar = new javax.swing.JButton();
        ActualizarCat_producto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        ModificarCat_producto.setText("Modificar");
        ModificarCat_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarCat_productoActionPerformed(evt);
            }
        });
        MenuCat_producto.add(ModificarCat_producto);

        EliminarCat_producto.setText("Eliminar");
        EliminarCat_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCat_productoActionPerformed(evt);
            }
        });
        MenuCat_producto.add(EliminarCat_producto);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Catalogo de Productos");

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla1.setComponentPopupMenu(MenuCat_producto);
        jScrollPane7.setViewportView(tabla1);

        txtCat_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCat_productoActionPerformed(evt);
            }
        });

        BuscarCat_producto.setText("Buscar");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel19.setText("Peso Superior en Mayoreo");

        txtPesoUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoUMActionPerformed(evt);
            }
        });

        jLabel18.setText("Peso Unitario en Mayoreo");

        jLabel17.setText("IVA");

        jLabel16.setText("Cantidad Minima del Producto");

        jLabel15.setText("ID del Departamento");

        jLabel14.setText("Peso Unitario en Venta ");

        jLabel13.setText("Peso Unitario en Compra");

        jLabel12.setText("Cantidad");

        jLabel11.setText("ID de la Unidad de Medida");

        jLabel10.setText("Descripcion del Producto");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPesoSM, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPesoUM, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCan_Produ, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboIDdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel14)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(91, 91, 91)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPesoUnitarioComp, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDesc_Produc)
                                    .addComponent(comboID_Unidad_Medida, 0, 159, Short.MAX_VALUE)
                                    .addComponent(txtPesoUnitarioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtDesc_Produc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(comboID_Unidad_Medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtPesoUnitarioComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPesoUnitarioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(comboIDdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtCan_Produ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18)
                        .addComponent(txtPesoUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPesoSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton11.setText("Guardar Datos");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        BotonConsultar.setText("Limpiar");
        BotonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarActionPerformed(evt);
            }
        });

        ActualizarCat_producto.setText("Actualizar");
        ActualizarCat_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarCat_productoActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(BotonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarCat_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActualizarCat_producto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtCat_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscarCat_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCat_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarCat_producto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        String  Desc_produc,Cantidad_medida,PesoUC,PesoUV,CanPro,Iva,PUM,PSM;

        String sql="";

        Desc_produc = txtDesc_Produc.getText();
        Cantidad_medida= txtCantidad.getText();
        PesoUC = txtPesoUnitarioComp.getText();
        PesoUV = txtPesoUnitarioVenta.getText();
        CanPro = txtCan_Produ.getText();
        Iva = txtIVA.getText();
        PUM = txtPesoUM.getText();
        PSM = txtPesoSM.getText();

        sql= "INSERT INTO cat_productos (DESC_PRODUCO,ID_UNIDAD_MEDIDA,CANTIDAD,P_U_COMPRA,P_U_VENTA,ID_DEPARTAMENTO,CANTIDAD_MIN,IVA,P_U_MAYOREO,P_S_MAYOREO) VALUES (?,?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement psd = cn.prepareStatement(sql);

            psd.setString(1,Desc_produc);
            int s = Integer.parseInt((String) comboID_Unidad_Medida.getSelectedItem());
            psd.setInt(2,s);
            psd.setString(3,Cantidad_medida);
            psd.setString(4,PesoUC);
            psd.setString(5,PesoUV);
            int l = Integer.parseInt((String) comboIDdescripcion.getSelectedItem());
            psd.setInt(6,l);
            psd.setString(7,CanPro);
            psd.setString(8,Iva);
            psd.setString(9,PUM);
            psd.setString(10,PSM);
            int n= psd.executeUpdate();

            if (n>0){

                JOptionPane.showMessageDialog(null, "REGISTRO GUARDADO CON EXITO");

            }
        } catch (SQLException ex) {
            Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtPesoUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoUMActionPerformed

    private void BotonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarActionPerformed

        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_BotonConsultarActionPerformed

    private void txtCat_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCat_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCat_productoActionPerformed

    private void ActualizarCat_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarCat_productoActionPerformed
        // TODO add your handling code here:
        try {
          
            String ID_PRODUCTO = idproduc;
            String DESC_PRODUC = txtDesc_Produc.getText();
            String s = comboID_Unidad_Medida.getSelectedItem().toString();
            String CANTIDAD = txtCantidad.getText();
            String PESOUNI = txtPesoUnitarioComp.getText();
            String PESOVENTA = txtPesoUnitarioVenta.getText();
            String l = comboIDdescripcion.getSelectedItem().toString();

            String CANPRODUC = txtCan_Produ.getText();
            String IVa = txtIVA.getText();
            String PESOUM = txtPesoUM.getText();
            String PESOSM = txtPesoSM.getText();

            PreparedStatement psd = cn.prepareStatement("UPDATE cat_productos SET DESC_PRODUCO='" +
                DESC_PRODUC +
                "',ID_UNIDAD_MEDIDA= '"
                +s+
                "',CANTIDAD= '"
                + CANTIDAD+
                "',P_U_COMPRA= '"
                +PESOUNI+
                "',P_U_VENTA= '"
                +PESOVENTA+
                "',ID_DEPARTAMENTO= '"
                + l +
                "',CANTIDAD_MIN= '"
                +CANPRODUC+
                "',IVA= '"
                + IVa+
                "',P_U_MAYOREO= '"
                +PESOUM    +
                "',P_S_MAYOREO= '"
                +PESOSM+
                "' WHERE ID_PRODUCTO= '"
                +ID_PRODUCTO + "'");

            int n = psd.executeUpdate();

            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Registro Actualizado");
            } else {
                JOptionPane.showMessageDialog(null, "No Se Puede Actualizar Tu Registro ");
            }
            catalogoproduc("");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ActualizarCat_productoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void ModificarCat_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarCat_productoActionPerformed
        // TODO add your handling code here:
        int fila = tabla1.getSelectedRow();
        idproduc = tabla1.getValueAt(fila, 0).toString();
        txtDesc_Produc.setText(tabla1.getValueAt(fila, 1).toString());
        comboID_Unidad_Medida.setSelectedItem(tabla1.getValueAt(fila, 2).toString());
        txtCantidad.setText(tabla1.getValueAt(fila, 3).toString());
        txtPesoUnitarioComp.setText(tabla1.getValueAt(fila, 4).toString());
        txtPesoUnitarioVenta.setText(tabla1.getValueAt(fila, 5).toString());
        comboIDdescripcion.setSelectedItem(tabla1.getValueAt(fila, 6).toString());
        txtCan_Produ.setText(tabla1.getValueAt(fila, 7).toString());
        txtIVA.setText(tabla1.getValueAt(fila, 8).toString());
        txtPesoUM.setText(tabla1.getValueAt(fila, 9).toString());
        txtPesoSM.setText(tabla1.getValueAt(fila, 10).toString());

    }//GEN-LAST:event_ModificarCat_productoActionPerformed

    private void EliminarCat_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCat_productoActionPerformed
        // TODO add your handling code here:
        int fila = tabla1.getSelectedRow();
        String cod="";
        cod=tabla1.getValueAt(fila, 0).toString();

        try {
            PreparedStatement pst;
            pst = cn.prepareStatement("DELETE FROM cat_productos WHERE  ID_PRODUCTO ='"+cod+"'");
            pst.executeUpdate();
            catalogoproduc("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Puedes Eliminar Esta FILA Hasta Borrar Sus Relaciones");
        }

    }//GEN-LAST:event_EliminarCat_productoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        desbloquear();
    }//GEN-LAST:event_jButton1ActionPerformed

 void catalogoproduc (String valor){
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("ID DEL PRODUCTO");
    modelo.addColumn("DESCRIPCION DEL PRODUCTO");
    modelo.addColumn("ID DE LA UNIDAD DE MEDIDA ");
    modelo.addColumn("CANTIDAD");
    modelo.addColumn("PESO UNITARIO EN COMPRA");
    modelo.addColumn("PESO UNITARIO EN VENTA");
    modelo.addColumn("ID DEL DEPARTAMENTO");
    modelo.addColumn("CANTIDAD MINIMA");
    modelo.addColumn("IVA");
    modelo.addColumn("PESO UNITARIO EN MAYOREO");
    modelo.addColumn("PESO SUPERIOR EN MAYOREO");
    tabla1.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM cat_productos";
    }
    else{
        sql="SELECT * FROM cat_productos WHERE ID_PRODUCTO='"+valor+"'";
    }
 
    String []datos = new String [11];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                modelo.addRow(datos);
            }
            tabla1.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(COnsul.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
 void cat_produ (){
 String sql="select * from cat_unidad_medida";
   

 
     try {
         Statement st = cn.createStatement();
         ResultSet rs =st.executeQuery(sql);
     while (rs.next())
     {
     comboID_Unidad_Medida.addItem(rs.getString("ID_UNIDAD_MEDIDA"));
     
     
     }
     
     
     
     } catch (SQLException ex) {
         Logger.getLogger(Cataloproduc.class.getName()).log(Level.SEVERE, null, ex);
     }
 
 
 
 
 
 }
 void cat_produ2 (){
 String sql="select * from cat_departamento";
   

 
     try {
         Statement st = cn.createStatement();
         ResultSet rs =st.executeQuery(sql);
     while (rs.next())
     {
     comboIDdescripcion.addItem(rs.getString("ID_DEPARTAMENTO"));
     
     
     }
     
     
     
     } catch (SQLException ex) {
         Logger.getLogger(Cataloproduc.class.getName()).log(Level.SEVERE, null, ex);
     }
 
 
 
 
 
 }
 conecta cc=new conecta ();
Connection cn=cc.conexion();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarCat_producto;
    private javax.swing.JButton BotonConsultar;
    private javax.swing.JButton BuscarCat_producto;
    private javax.swing.JMenuItem EliminarCat_producto;
    private javax.swing.JPopupMenu MenuCat_producto;
    private javax.swing.JMenuItem ModificarCat_producto;
    private javax.swing.JComboBox<String> comboID_Unidad_Medida;
    private javax.swing.JComboBox<String> comboIDdescripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txtCan_Produ;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCat_producto;
    private javax.swing.JTextField txtDesc_Produc;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtPesoSM;
    private javax.swing.JTextField txtPesoUM;
    private javax.swing.JTextField txtPesoUnitarioComp;
    private javax.swing.JTextField txtPesoUnitarioVenta;
    // End of variables declaration//GEN-END:variables
}
