/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño;

import anidaciones.users;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zabdy
 */
public class Catalogocaja extends javax.swing.JInternalFrame {

    /**
     * Creates new form Catalogocaja
     */
    public Catalogocaja() {
        initComponents();
        catalocaja("");
        bloquear();
        datocj();
  codigosclientes();
    }
     String idcaja;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuCatalogoCaja = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        EliminarCat_caja = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        txtdisponi = new javax.swing.JTextField();
        txtdscaja = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtfolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtusu = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablacaja = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        botncaja = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        BotonActualizarCat_caja = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtbuscar_Cat_caja = new javax.swing.JTextField();
        BuscarCat_caja = new javax.swing.JButton();

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        MenuCatalogoCaja.add(Modificar);

        EliminarCat_caja.setText("Eliminar");
        EliminarCat_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCat_cajaActionPerformed(evt);
            }
        });
        MenuCatalogoCaja.add(EliminarCat_caja);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Catalogo de Caja");

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Descripcion de la Caja");

        jLabel6.setText("Disponibilidad de la Caja");

        jLabel7.setText("ID Del Usuario");

        combo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo1MouseClicked(evt);
            }
        });
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Folio:");

        jLabel2.setText("Nombre Del Usuario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdscaja)
                    .addComponent(txtdisponi)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo1, 0, 134, Short.MAX_VALUE)
                            .addComponent(txtfolio)
                            .addComponent(txtusu))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdscaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdisponi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tablacaja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablacaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablacaja.setComponentPopupMenu(MenuCatalogoCaja);
        jScrollPane4.setViewportView(tablacaja);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botncaja.setText("Guardar Datos");
        botncaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botncajaActionPerformed(evt);
            }
        });

        jButton14.setText("Limpiar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        BotonActualizarCat_caja.setText("Actualizar");
        BotonActualizarCat_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarCat_cajaActionPerformed(evt);
            }
        });

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botncaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonActualizarCat_caja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botncaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonActualizarCat_caja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        BuscarCat_caja.setText("Buscar");
        BuscarCat_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCat_cajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtbuscar_Cat_caja, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BuscarCat_caja, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtbuscar_Cat_caja)
                    .addComponent(BuscarCat_caja, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 void codigosclientes(){
     int j;
        int cont=1;
        String num="";
        String c="";
         String SQL="select max(folio_actual) from cat_cajas";
       // String SQL="select count(*) from factura";
   //     String SQL="SELECT MAX(folio_actual) AS folio_actual FROM cat_caja";
        //String SQL="SELECT @@identity AS ID";
        try {
            Statement st = cn.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            if(rs.next())
            {              
                 c=rs.getString(1);
            }
           
                  
            if(c==null){
                txtfolio.setText("CC0001");
            }
            else{
                char r1=c.charAt(2);
            char r2=c.charAt(3);
            char r3=c.charAt(4);
            char r4=c.charAt(5);
            String r="";
            r=""+r1+r2+r3+r4;
            
                 j=Integer.parseInt(r);
                 codigos gen= new codigos();
                 gen.generar(j);
                 txtfolio.setText("CC"+gen.serie());
                
            
            }
       
          
                  
           
           
         
        } catch (SQLException ex) {
           Logger.getLogger(IngresoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      
    void bloquear(){
txtbuscar_Cat_caja.setEnabled(false);
txtdisponi.setEnabled(false);
txtdscaja.setEnabled(false);
combo1.setEnabled(false);
jButton1.setEnabled(true);
botncaja.setEnabled(false);
jButton14.setEnabled(false);
BotonActualizarCat_caja.setEnabled(false);
jButton2.setEnabled(false);
}
 void desbloquear(){
txtbuscar_Cat_caja.setEnabled(true);
txtdisponi.setEnabled(true);
txtdscaja.setEnabled(true);
combo1.setEnabled(true);
jButton1.setEnabled(false);
botncaja.setEnabled(true);
jButton14.setEnabled(true);
BotonActualizarCat_caja.setEnabled(true);
jButton2.setEnabled(true);
}   
    
    void limpiar(){
    
                txtbuscar_Cat_caja.setText("");
                       txtdisponi.setText("");
                       txtdscaja.setText("");
    }
    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        String sql="select*from users where id_user='"+this.combo1.getSelectedItem()+"'";
        try {
         
         
            Statement st = cn.createStatement();
         ResultSet rs =st.executeQuery(sql);
     rs.next();
     this.txtusu.setText(String.valueOf(rs.getString("user_name")));             
     
     
     
        
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed

    private void BuscarCat_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCat_cajaActionPerformed
        // TODO add your handling code here:
        catalocaja(txtbuscar_Cat_caja.getText());
    }//GEN-LAST:event_BuscarCat_cajaActionPerformed

    private void botncajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botncajaActionPerformed
        // TODO add your handling code here:

        String  paterR,materR,R;

        String sql="";

        paterR = txtdscaja.getText();
        materR = txtdisponi.getText();
        R = txtfolio.getText();
        sql= "INSERT INTO cat_cajas (DESC_CAJA,DISPONIBLE,ID_USER,folio_actual) VALUES (?,?,?,?)";
        try {
            PreparedStatement psd = cn.prepareStatement(sql);

            psd.setString(1,paterR);
            psd.setString(2,materR);
            
            int s = Integer.parseInt((String) combo1.getSelectedItem());
            psd.setInt(3,s);
            psd.setString(4,R);
            int n= psd.executeUpdate();
            if (n>0){

                JOptionPane.showMessageDialog(null, "REGISTRO GUARDADO CON EXITO");

            }
        } catch (SQLException ex) {
            Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botncajaActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
                // TODO add your handling code here:
               limpiar();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void BotonActualizarCat_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarCat_cajaActionPerformed
        // TODO add your handling code here:
        try {
            
            String ID_CAJA = idcaja;
            String DESC_caja = txtdscaja.getText();
            String DIS_caja = txtdisponi.getText();
            String Num_usuario = combo1.getSelectedItem().toString();
            String txfoli = txtfolio.getText();
            PreparedStatement psd = cn.prepareStatement("UPDATE cat_cajas SET DESC_CAJA='" +
                DESC_caja +
                "',DISPONIBLE= '"
                + DIS_caja +
                "',USUARIO='"
                + Num_usuario+

                "' WHERE ID_CAJA= '"
                +ID_CAJA + "'");

            int n = psd.executeUpdate();
            System.out.println(n);
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Registro Actualizado");
            } else {
                JOptionPane.showMessageDialog(null, "No Se Puede Actualizar Tu Registro ");
            }
            catalocaja("");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_BotonActualizarCat_cajaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        desbloquear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        int fila = tablacaja.getSelectedRow();

        idcaja = tablacaja.getValueAt(fila, 0).toString();
        txtdscaja.setText(tablacaja.getValueAt(fila, 1).toString());
        txtdisponi.setText(tablacaja.getValueAt(fila, 2).toString());

        combo1.setSelectedItem(tablacaja.getValueAt(fila, 3).toString());

    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarCat_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCat_cajaActionPerformed
        // TODO add your handling code here:
        int fila = tablacaja.getSelectedRow();
        String cod="";
        cod=tablacaja.getValueAt(fila, 0).toString();

        try {
            PreparedStatement pst;
            pst = cn.prepareStatement("DELETE FROM cat_caja WHERE  ID_CAJA ='"+cod+"'");
            pst.executeUpdate();
            catalocaja("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Puedes Eliminar Esta FILA Hasta Borrar Sus Relaciones");
        }

    }//GEN-LAST:event_EliminarCat_cajaActionPerformed

    private void combo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo1MouseClicked
        // TODO add your handling code here:
 
    }//GEN-LAST:event_combo1MouseClicked
 void catalocaja (String valor){
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("ID DE LA CAJA");
    modelo.addColumn("DESCRIPCION DE LA CAJA");
    modelo.addColumn("DISPONIBILIDAD");
    modelo.addColumn("USUARIO");
    
    
    tablacaja.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM cat_cajas";
    }
    else{
        sql="SELECT * FROM cat_cajas WHERE ID_CAJA='"+valor+"'";
    }
 
    String []datos = new String [4];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
               
                modelo.addRow(datos);
            }
            tablacaja.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(COnsul.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
 private void datocj (){
 
 String sql="select * from users ";
   try {
         Statement st = cn.createStatement();
         ResultSet rs =st.executeQuery(sql);
     while (rs.next())
     {

     

              combo1.addItem(rs.getString("id_user"));


     }
     
     
     
     } catch (SQLException ex) {
         Logger.getLogger(Catalogocaja.class.getName()).log(Level.SEVERE, null, ex);
     }
 
 
 
 }
 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarCat_caja;
    private javax.swing.JButton BuscarCat_caja;
    private javax.swing.JMenuItem EliminarCat_caja;
    private javax.swing.JPopupMenu MenuCatalogoCaja;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JButton botncaja;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablacaja;
    private javax.swing.JTextField txtbuscar_Cat_caja;
    private javax.swing.JTextField txtdisponi;
    private javax.swing.JTextField txtdscaja;
    private javax.swing.JTextField txtfolio;
    private javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
conecta cc=new conecta ();
Connection cn=cc.conexion();
}
