/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxEditor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zabdy
 */
public class TbVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form TbVenta
     */
    public TbVenta() {
        initComponents();
        datocj();
        mostrartipo();
        usari();
    bloquear();
        cataloVENTAS("");
    cat_produ();
     txtfecha.setDisabledTextColor(Color.blue);
        txtfecha.setText(fechaact());
    }
    String folio = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
         void bloquear(){
                txtCantidad.setEnabled(true);
    txtIva.setEnabled(false);
    txtPesoUni.setEnabled(false);
    txtCantidad.setEnabled(false);
    comboID_Producto.setEnabled(false);
    txtbuscar.setEnabled(false);
    txtfecha.setEnabled(false);
    txtotal.setEnabled(false);
    comboidcatalogo.setEnabled(false);
    comboven.setEnabled(false);
    idusu.setEnabled(false);
    botonventas.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(true);
    jButton5.setEnabled(false);
    jButton6.setEnabled(true);
    }
         void desbloquear(){
    txtIva.setEnabled(true);
    txtPesoUni.setEnabled(true);
    txtCantidad.setEnabled(true);
    comboID_Producto.setEnabled(true);
    txtbuscar.setEnabled(true);
    txtfecha.setEnabled(true);
    txtotal.setEnabled(true);
    comboidcatalogo.setEnabled(true);
    comboven.setEnabled(true);
    idusu.setEnabled(true);
    botonventas.setEnabled(true);
    jButton2.setEnabled(true);
    jButton3.setEnabled(true);
    jButton4.setEnabled(false);
    jButton5.setEnabled(true);
    jButton6.setEnabled(true);
         }
          void limpiar(){
         txtbuscar.setText("");
    txtfecha.setText("");
    txtotal.setText("");
    
    
         }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventas1 = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        idusu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboven = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboidcatalogo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        txtPesoUni = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        comboID_Producto = new javax.swing.JComboBox<>();
        txtNomCaja = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNomUsuario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        botonventas = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jMenuItem1.setText("modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jButton1.setText("Consultar Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tabla Ventas");

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setName(""); // NOI18N

        tablaventas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaventas1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tablaventas1);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Fecha Ejemplo: (2016-01-30)");

        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });

        jLabel2.setText("ID del Usuario");

        idusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idusuActionPerformed(evt);
            }
        });

        jLabel3.setText("Total de Ventas");

        jLabel4.setText("ID del Catalogo Caja");

        comboven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combovenActionPerformed(evt);
            }
        });

        jLabel5.setText("ID Cliente");

        comboidcatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboidcatalogoActionPerformed(evt);
            }
        });

        jLabel6.setText("Producto");

        jLabel8.setText("Cantidad de Piezas");

        jLabel9.setText("Peso Unitario");

        jLabel10.setText("Iva");

        txtNomCaja.setText(" ");

        jLabel7.setText("Nombre de la caja");

        jLabel11.setText("Nombre Cliente");

        jLabel12.setText("Nombre del Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboID_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPesoUni, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNomCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboven, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                                    .addComponent(txtfecha, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(idusu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(comboidcatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(idusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel4)
                        .addComponent(comboven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(comboidcatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboID_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesoUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonventas.setText("Guardar Datos");
        botonventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonventasActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Nuevo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonventas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Ventas");
        jPanel2.getAccessibleContext().setAccessibleDescription("Ventas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonventasActionPerformed
// TODO add your handling code here:
venta();
    }//GEN-LAST:event_botonventasActionPerformed
public static String fechaact(){
    Date fecha= new Date();
    SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/YYYY");
    return formatofecha.format(fecha);
    


}    
    void venta(){
conecta cc = new conecta();
        Connection cn = cc.conexion();
        String Total, vent,Fecha,cant,pesouni,iva;
          
        String sql = "";

        Total = txtotal.getText();
        Fecha = txtfecha.getText();
        cant=txtCantidad.getText();
        pesouni=txtPesoUni.getText();
        iva=txtIva.getText();
        sql = "INSERT INTO ventas (FECHA,ID_USER_NAME,TOTAL,ID_CAJA,ID_CLIENTE,ID_PRODUCTO,CANTIDAD,P_UNITARIO,IVA) VALUES (?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement psd = cn.prepareStatement(sql);

            psd.setString(1, Fecha);

            int s = Integer.parseInt((String) idusu.getSelectedItem());
            psd.setInt(2, s);
            psd.setString(3, Total);
            int l = Integer.parseInt((String) comboven.getSelectedItem());
            psd.setInt(4, l);
              String q = comboidcatalogo.getSelectedItem().toString();
            psd.setString(5, q);
              String p = comboID_Producto.getSelectedItem().toString();
            psd.setString(6, p);
            psd.setString(7, cant);
            psd.setString(8, pesouni);
            psd.setString(9, iva);
            int n = psd.executeUpdate();
            
            cataloVENTAS("");
            if (n > 0) {

                JOptionPane.showMessageDialog(null, "REGISTRO GUARDADO CON EXITO");

            }
        } catch (SQLException ex) {
            Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cataloVENTAS("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cataloVENTAS(txtbuscar.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int fila = tablaventas1.getSelectedRow();
        //if(fila>=0){

        txtfecha.setText(tablaventas1.getValueAt(fila, 1).toString());
        idusu.setSelectedItem(tablaventas1.getValueAt(fila, 2).toString());
        txtotal.setText(tablaventas1.getValueAt(fila, 3).toString());
        comboven.setSelectedItem(tablaventas1.getValueAt(fila, 4).toString());
        comboidcatalogo.setSelectedItem(tablaventas1.getValueAt(fila, 5).toString());
         comboID_Producto.setSelectedItem(tablaventas1.getValueAt(fila, 6).toString());
         txtCantidad.setText(tablaventas1.getValueAt(fila, 7).toString());
         txtPesoUni.setText(tablaventas1.getValueAt(fila, 8).toString());
         txtIva.setText(tablaventas1.getValueAt(fila, 9).toString());
        //String Codigo =String.valueOf(tablaventas.getValueAt(fila, 6));
        folio = tablaventas1.getValueAt(fila, 0).toString();
        //}
        //else{
        //JOptionPane.showMessageDialog(null,"no seleciono fila");
        //}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            String FOLIO = folio;
            String Total = txtotal.getText();
            
            String fecha = txtfecha.getText();
            String s = idusu.getSelectedItem().toString();
            String l = comboven.getSelectedItem().toString();
            String q = comboidcatalogo.getSelectedItem().toString();
            PreparedStatement psd = cn.prepareStatement("UPDATE ventas SET FECHA='" +
                    fecha +
                    "',ID_USER_NAME= '"
                    + s + 
                    "',TOTAL='" 
                    + Total + 
                    "',ID_CAJA='"
                    +l+
                    "',ID_CLIENTE ='"
                    +q+
                    "' WHERE FOLIO= '"
                    +FOLIO + "'");            
            
            
            
            int n = psd.executeUpdate();
            System.out.println(n);
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Registro actualizado");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo");
            }
            cataloVENTAS("");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int fila = tablaventas1.getSelectedRow();
    String cod="";
    cod=tablaventas1.getValueAt(fila, 0).toString();
    
    try {
        PreparedStatement pst;
            pst = cn.prepareStatement("DELETE FROM ventas WHERE  FOLIO ='"+cod+"'");
        pst.executeUpdate();
        cataloVENTAS("");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No Puedes Eliminar Esta FILA Hasta Borrar Sus Relaciones");
    }
        
        
    
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        desbloquear();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void comboidcatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboidcatalogoActionPerformed
        // TODO add your handling code here:}
                String sql="select*from cat_cliente where idcat_cliente='"+this.comboidcatalogo.getSelectedItem()+"'";
        try {
         
         
     Statement st = cn.createStatement();
     ResultSet rs =st.executeQuery(sql);
     rs.next();
     this.txtNombreCliente.setText(String.valueOf(rs.getString("nombre")));             
     
     
     
        
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_comboidcatalogoActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void idusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idusuActionPerformed
        // TODO add your handling code here:
                String sql="select*from users where id_user='"+this.idusu.getSelectedItem()+"'";
        try {
         
         
            Statement st = cn.createStatement();
         ResultSet rs =st.executeQuery(sql);
     rs.next();
     this.txtNomUsuario.setText(String.valueOf(rs.getString("user_name")));             
     
     
     
        
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_idusuActionPerformed

    private void combovenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combovenActionPerformed
        // TODO add your handling code here:
                String sql="select*from cat_cajas where id_caja='"+this. comboven.getSelectedItem()+"'";
        try {
         
         
            Statement st = cn.createStatement();
         ResultSet rs =st.executeQuery(sql);
     rs.next();
     this.txtNomCaja.setText(String.valueOf(rs.getString("desc_caja")));             
     
     
     
        
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_combovenActionPerformed
    
    void datocj() {

        String sql = "select * from cat_cajas";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                comboven.addItem(rs.getString("ID_CAJA"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(TbVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    void cat_produ (){
 String sql="select * from cat_productos";
   

 
     try {
         Statement st = cn.createStatement();
         ResultSet rs =st.executeQuery(sql);
     while (rs.next())
     {
     comboID_Producto.addItem(rs.getString("desc_producto"));
     
     
     }
     
     
     
     } catch (SQLException ex) {
         Logger.getLogger(detalles.class.getName()).log(Level.SEVERE, null, ex);
     }
 
 
 
 
 
 }
    void usari() {

        String sql = "select * from users";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idusu.addItem(rs.getString("id_user"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(TbVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
//combo de catalgo cliente
    void mostrartipo() {
        String sql = "select * from cat_cliente";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                comboidcatalogo.addItem(rs.getString("idcat_cliente"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(TbVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
     void cataloVENTAS(String dato){
        String [] Titulo = {"ID DEL PRODUCTO","ID DE LA VENTA","CANTIDAD","PESO UNITARIO"};
        DefaultTableModel tabla = new DefaultTableModel(null,Titulo);
    String []Registro= new String[4];
    String mostrar="SELECT * FROM detalle_ventas WHERE CONCAT (idproducto,'',id_venta) LIKE '%"+dato+"%'"; 
    Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs =st.executeQuery(mostrar);
            while(rs.next())
            {
                Registro[0]=rs.getString(1);
                Registro[1]=rs.getString(2);
                Registro[2]=rs.getString(3);
                Registro[3]=rs.getString(4);
                tabla.addRow(Registro);
            }
            tablaventas1.setModel(tabla);
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    
    
    }
  
    
    
    
/*void cataloVENTAS(String valor){
    String mostrar="SELECT * FROM ventas INNER JOIN detalle_ventas ON ventas.id_venta= detalle_ventas.id_venta WHERE (id_user) LIKE '%"+valor+"%'";
    String []titulos={"Id de la venta","folio","fecha","id del usuario","total","id caja","id cliente","serie","Cancelado","id del producto","id de la venta","cantidad","peso unitario","iva"};
    String []Registros=new String[14];
        DefaultTableModel model = new DefaultTableModel(null,titulos);
  
        try {
              Statement st = cn.createStatement();
              ResultSet rs = st.executeQuery(mostrar);
              while(rs.next())
              {
                  Registros[0]= rs.getString(1);
                  Registros[1]= rs.getString(2);
                  Registros[2]= rs.getString(3);
                  Registros[3]= rs.getString(4);
                  Registros[4]= rs.getString(5);
                  Registros[5]= rs.getString(6);
                  Registros[6]= rs.getString(7);
                  Registros[7]= rs.getString(8);
                  Registros[8]= rs.getString(9);
                  Registros[9]= rs.getString(10);
                  Registros[10]= rs.getString(11);
                  Registros[11]= rs.getString(12);
                  Registros[12]= rs.getString(13);
                  Registros[13]= rs.getString(14);
                  
                  
                  
                 
                  
                  model.addRow(Registros);
              }
              tablaventas1.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(IngresoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    
  }
  
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonventas;
    private javax.swing.JComboBox<String> comboID_Producto;
    private javax.swing.JComboBox<String> comboidcatalogo;
    private javax.swing.JComboBox<String> comboven;
    private javax.swing.JComboBox<String> idusu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaventas1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNomCaja;
    private javax.swing.JTextField txtNomUsuario;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPesoUni;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtotal;
    // End of variables declaration//GEN-END:variables
    conecta cc = new conecta();
    Connection cn = cc.conexion();
}
